# Generated by Django 5.1.4 on 2024-12-15 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventas',
            name='fechahora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
