# Generated by Django 5.1.4 on 2024-12-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appventas', '0002_alter_detalleventas_fechahora_alter_ventas_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('precio_unitario', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='detalleventas',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
