# Generated by Django 5.1.4 on 2024-12-16 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appventas', '0003_insumo_detalleventas_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventas',
            name='insumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appventas.insumo'),
        ),
    ]
